[package]
name = "bakery"
description = "A simple static site generator."
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
atom_syndication = { version = "0.11", features = ["with-serde"] }
chrono = "0.4"
clap = "3.0.0-beta.5"
fs_extra = "1"
glob = "0.3"
grass = { version = "0.10", default-features = false, features = ["random"] }
gray_matter = "0.2"
pulldown-cmark = "0.8"
rayon = "1.5"
serde = "1"
serde_json = "1"
tera = "1.15"
thiserror = "1"
toml = "0.5"
url = { version = "2", features = ["serde"] }