[package]
name = "bakery"
version = "0.1.0"
edition = "2021"

[dependencies]
atom_syndication = { version = "0.11", features = ["with-serde"] }
chrono = "0.4"
glob = "0.3"
grass = { version = "0.10", default-features = false, features = ["random"] }
gray_matter = "0.2"
katex = "0.4"
nom = "7"
pulldown-cmark = "0.8"
serde = "1"
serde_json = "1"
tera = "1.15"
thiserror = "1"
walkdir = "2"